### ISSUE TITLE
老哥们，怎么把密码搞上来了

### ISSUE THREAD

**Issue by Chronostasys** [Pivot-Studio/CSE_Student_Innovation_Project#3]
https://github.com/Pivot-Studio/CSE_Student_Innovation_Project/blob/55df1cf3fa241eda0ec98474d46449f80596baf0/pkg/services/email_sender.go#L26  
这种敏感信息的东西不要放上来，可以存入json文件，然后启动时读取。（json文件放入gitignore中）   
@Xieyuschen @1720648723

**Comment by 1720648723** [comment]
哈哈哈哈，幸亏这个密码是错的
